import {useCallback,useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import type {History,Session,Snapshot,Train} from './types';
import {ApiError,login,request,setCsrf} from './api';
import {duration,effect,level,location,movement,severity,visibleTrains} from './utils';
import RailMap from './RailMap';
import {IncidentDialog,Modal,OperationError,TrainDialog,TransferDialog} from './Dialogs';
import Infrastructure from './Infrastructure';

type Dialog={kind:'train';train?:Train}|{kind:'transfer';train:Train}|{kind:'incident';target?:{type:string;id:string}}|{kind:'station';id:string}|{kind:'about'}|{kind:'delete';train:Train}|null;
function Logo(){return <div className="brand"><svg viewBox="0 0 40 40" aria-hidden="true"><rect width="40" height="40" rx="11" fill="currentColor"/><path d="M13 9h14v18H13zM15 31l3-4m7 4-3-4M14 18h12" fill="none" stroke="#0b1220" strokeWidth="3"/><circle cx="17" cy="23" r="1.5" fill="#0b1220"/><circle cx="23" cy="23" r="1.5" fill="#0b1220"/></svg><div>ferrovia<span>CENTRO DE OPERAÇÕES</span></div></div>;}
function Login({onLogin}:{onLogin:()=>Promise<void>}){
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{await login(String(f.get('username')),String(f.get('password')));await onLogin();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
  return <div className="login-page"><div className="login-story"><Logo/><span className="eyebrow">VISIBILIDADE DE PONTA A PONTA</span><h1>Uma rede.<br/>Cada movimento<br/><em>sob controle.</em></h1><p>Composições, estações e ocorrências em uma visão integrada da operação ferroviária.</p><div className="login-lines"><i/><i/><i/><i/></div><span className="muted">São Paulo como referência · ambiente de simulação</span></div><form onSubmit={submit} className="login-card"><span className="eyebrow">ACESSO À OPERAÇÃO</span><h2>Bem-vindo à central</h2><p className="muted">Entre com sua conta para acompanhar a rede.</p><label>Usuário<input name="username" autoComplete="username" placeholder="admin, operator ou viewer" required autoFocus/></label><label>Senha<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<p className="error-box" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Entrando…':'Acessar central →'}</button><p className="login-note">No primeiro acesso local, a senha de admin aparece no terminal do servidor. As contas adicionais são habilitadas pela configuração do ambiente.</p></form></div>;
}
export default function App(){
  const [session,setSession]=useState<Session|null>(null),[initializing,setInitializing]=useState(true),[snap,setSnap]=useState<Snapshot|null>(null),[connected,setConnected]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [tab,setTab]=useState('map'),[line,setLine]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[dialog,setDialog]=useState<Dialog>(null),[history,setHistory]=useState<History[]>([]),[showResolved,setShowResolved]=useState(false);
  const version=useRef(-1),fetching=useRef(false),seenIncidents=useRef<Set<string>|null>(null);
  const apply=useCallback((data:Snapshot)=>{if(data.network.version>=version.current){version.current=data.network.version;setSnap(data);setConnected(true);const open=Object.values(data.network.incidents).filter(i=>i.status!=='RESOLVED');if(seenIncidents.current){const added=open.filter(i=>!seenIncidents.current!.has(i.id));if(added.length)setNotice(`Novo alerta: ${added.map(i=>i.label).join('; ')}`);}seenIncidents.current=new Set(open.map(i=>i.id));}},[]);
  const loadSession=useCallback(async()=>{try{const value=await request<Session>('/api/v1/session');setCsrf(value.csrf,value.csrfHeader);setSession(value);}catch(e){if(!(e instanceof ApiError)||e.status!==401)setError((e as Error).message);setSession(null);}finally{setInitializing(false);}},[]);
  const refresh=useCallback(async()=>{if(fetching.current)return;fetching.current=true;try{apply(await request<Snapshot>('/api/v1/network'));}catch(e){setConnected(false);if(e instanceof ApiError&&e.status===401){setSession(null);setSnap(null);version.current=-1;seenIncidents.current=null;}else setError((e as Error).message);}finally{fetching.current=false;}},[apply]);
  useEffect(()=>{void loadSession();},[loadSession]);
  useEffect(()=>{if(!session)return;void refresh();const stream=new EventSource('/api/v1/events');stream.addEventListener('version',e=>{if(Number((e as MessageEvent).data)!==version.current)void refresh();});stream.onerror=()=>setConnected(false);const interval=window.setInterval(()=>void refresh(),5000);return()=>{stream.close();window.clearInterval(interval);};},[session,refresh]);
  useEffect(()=>{if(!session||tab!=='history')return;let live=true;const load=()=>request<History[]>('/api/v1/history').then(data=>{if(live)setHistory(data);}).catch(e=>{if(live)setError(e.message);});void load();const interval=window.setInterval(()=>void load(),5000);return()=>{live=false;clearInterval(interval);};},[session,tab]);
  async function action(path:string,body?:unknown,method?:string){if(busy)return false;setBusy(true);setError('');try{const data=await request<Snapshot>('/api/v1'+path,body,method);apply(data);return true;}catch(e){setError((e as Error).message);if(e instanceof ApiError&&e.status===401)setSession(null);return false;}finally{setBusy(false);}}
  async function transfer(t:Train){if(snap?.network.running&&!await action('/clock',{running:false,timeScale:snap.network.timeScale}))return;setDialog({kind:'transfer',train:t});}
  if(initializing)return <div className="loading"><Logo/><p>Conectando à central…</p></div>;
  if(!session)return <Login onLogin={loadSession}/>;
  if(!snap)return <div className="loading"><Logo/><p>{error||'Carregando rede…'}</p><button onClick={()=>void refresh()}>Tentar novamente</button></div>;
  const n=snap.network,m=snap.metrics,admin=session.roles.includes('ROLE_ADMIN'),operate=admin||session.roles.includes('ROLE_OPERATOR'),chosen=n.trains[selected],trains=visibleTrains(n,line,query);
  const incidents=Object.values(n.incidents).filter(i=>showResolved||i.status!=='RESOLVED').sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  return <OperationError.Provider value={error}><div className="app"><header className="topbar"><Logo/><div className="header-context"><span className="eyebrow">SUPERVISÃO DA REDE</span><strong>São Paulo <span className="badge">REFERÊNCIA 2024</span></strong></div><div className="header-right"><span className={`connection ${connected?'':'offline'}`}><i/>{connected?'Conectado':'Reconectando'}</span><button className="text-button" onClick={()=>setDialog({kind:'about'})}>Sobre o cenário</button><div className="user-chip"><span>{session.username.slice(0,1).toUpperCase()}</span>{session.username}</div><button className="text-button" onClick={async()=>{try{await request('/logout',{},'POST');setSession(null);setSnap(null);version.current=-1;seenIncidents.current=null;setDialog(null);}catch(e){setError((e as Error).message);}}}>Sair</button></div></header>
    <div className="page-heading"><div><span className="eyebrow">VISÃO OPERACIONAL</span><h1>Todos os movimentos. Uma central.</h1><p className="muted">Acompanhe a circulação, gerencie a frota e responda às ocorrências.</p></div><div className="clock-control"><div className="simulation-clock"><small>TEMPO SIMULADO</small><strong>{duration(n.elapsedSeconds)}</strong></div><select aria-label="Velocidade da simulação" value={n.timeScale} disabled={!operate||busy} onChange={e=>void action('/clock',{running:n.running,timeScale:Number(e.target.value)})}>{[.5,1,5,10,30,60].map(speed=><option key={speed} value={speed}>{speed}×</option>)}{![.5,1,5,10,30,60].includes(n.timeScale)&&<option value={n.timeScale}>{n.timeScale}×</option>}</select><button className={n.running&&!snap.fault?'':'primary'} disabled={!operate||busy} onClick={()=>void action('/clock',{running:!n.running||!!snap.fault,timeScale:n.timeScale})}>{n.running&&!snap.fault?'Ⅱ Pausar':'▶ Iniciar'}</button><button title="Avançar 10 segundos simulados" disabled={!operate||busy||n.running} onClick={()=>void action('/step',{seconds:10})}>+10 s</button></div></div>
    {snap.fault&&<p className="error-box" role="alert">{snap.fault}</p>}
    <section className="metrics" aria-label="Indicadores da rede"><div className="metric"><span>Trens em circulação <i>↗</i></span><strong>{m.active.toString().padStart(2,'0')}<small>/ {m.total} cadastrados</small></strong><p><span className="dot green"/>{m.moving} em movimento agora</p></div><div className="metric"><span>Linhas monitoradas <i>⌁</i></span><strong>{Object.keys(n.lines).length}<small>linhas</small></strong><p>{Object.keys(n.stations).length} estações na rede</p></div><div className={`metric ${m.openIncidents?'alert-metric':''}`}><span>Ocorrências abertas <i>△</i></span><strong>{m.openIncidents.toString().padStart(2,'0')}<small>ocorrências</small></strong><p>{snap.impacts.length?`${new Set(snap.impacts.map(i=>i.lineId)).size} linhas sinalizadas`:'Nenhum alerta ativo'}</p></div><div className="metric"><span>Espera acumulada média <i>◷</i></span><strong>{Math.round(m.meanDelay)}<small>segundos / trem ativo</small></strong><p>{m.waiting} aguardando ou bloqueados</p></div></section>
    <div className="workspace-toolbar"><nav aria-label="Seções do painel">{[['map','Mapa da rede'],['fleet','Frota'],['incidents','Ocorrências'],...(admin?[['infrastructure','Infraestrutura']]:[]),['history','Histórico']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='incidents'&&m.openIncidents>0&&<span className="count">{m.openIncidents}</span>}</button>)}</nav><div className="toolbar-actions">{operate&&<><button onClick={()=>setDialog({kind:'incident'})} disabled={busy}>△ Nova ocorrência</button><button className="primary" onClick={()=>setDialog({kind:'train'})} disabled={busy}>+ Nova composição</button></>}</div></div>
    {(tab==='map'||tab==='fleet')&&<div className="network-workspace"><aside className="line-sidebar"><div className="sidebar-title"><h3>Linhas da rede</h3><span>{Object.keys(n.lines).length}</span></div><button className={`line-item all-lines ${!line?'selected':''}`} onClick={()=>setLine('')}><span className="line-symbol">⌘</span><span>Toda a rede<small>Visão integrada</small></span><b>{m.active}</b></button><div className="line-list">{Object.values(n.lines).map(l=>{const impacts=snap.impacts.filter(i=>i.lineId===l.id),direct=impacts.some(i=>i.level!=='POTENTIAL');return <button key={l.id} className={`line-item ${line===l.id?'selected':''}`} onClick={()=>setLine(line===l.id?'':l.id)} style={{'--line-color':l.color} as React.CSSProperties}><span className="line-number">{l.id.substring(1)}</span><span>{l.name.split('·')[1]?.trim()??l.name}<small>{!l.enabled?'Desativada':impacts.length?direct?'Impacto operacional':'Risco por integração':'Operação disponível'}</small></span><b>{m.byLine[l.id]??0}</b>{impacts.length>0&&<i className={direct?'alert-dot':'risk-dot'}/>}</button>;})}</div><div className="sidebar-note"><span className="live-dot"/>{n.running&&!snap.fault?'Simulação em execução':'Simulação pausada'}<small>Atualização #{n.version}</small></div></aside>
      <main className="network-main"><div className="network-heading"><div><h2>{line?n.lines[line].name:tab==='map'?'Mapa da rede':'Composições da rede'}</h2><p>{trains.filter(t=>t.active).length} em circulação{line?` · ${n.lines[line].operator}`:' · todas as linhas'}</p></div><input className="search" aria-label="Buscar composição ou estação" placeholder="Buscar composição ou estação…" value={query} onChange={e=>setQuery(e.target.value)}/></div>
        {tab==='map'?<RailMap n={n} impacts={snap.impacts} line={line} query={query} selected={selected} onTrain={setSelected} onStation={id=>setDialog({kind:'station',id})}/>:<div className="table-scroll fleet-table"><table><thead><tr><th>Composição</th><th>Linha atual</th><th>Posição</th><th>Estado</th><th>Velocidade</th><th>Espera</th></tr></thead><tbody>{trains.map(t=><tr key={t.id} className={selected===t.id?'selected-row':''} onClick={()=>setSelected(t.id)}><td><button className="train-link" onClick={()=>setSelected(t.id)}>{t.number}<small>{t.id}</small></button></td><td><span className="line-pill" style={{borderColor:n.lines[t.currentLineId].color}}>{n.lines[t.currentLineId].name}</span></td><td>{location(n,t)}</td><td><span className={`badge ${t.movement==='BLOCKED'?'warning':t.active?'ok':''}`}>{movement[t.movement]}</span></td><td>{Math.round(t.speedKmh)} km/h</td><td>{Math.round(t.delaySeconds)} s</td></tr>)}</tbody></table>{!trains.length&&<div className="empty">Nenhuma composição corresponde ao filtro.</div>}</div>}
        {line&&snap.impacts.some(i=>i.lineId===line)&&<div className="line-impact-list">{snap.impacts.filter(i=>i.lineId===line).map(i=><div key={i.incidentId}><span className={`badge ${i.level==='POTENTIAL'?'risk':'warning'}`}>{level[i.level]}</span><strong>{i.label}</strong><small>{i.path.join(' → ')} · {i.reason}</small></div>)}</div>}
      </main><aside className="detail-sidebar">{chosen?<><div className="sidebar-title"><span className="eyebrow">COMPOSIÇÃO SELECIONADA</span><button className="text-button" onClick={()=>setSelected('')} aria-label="Limpar seleção">×</button></div><div className="train-identity"><span style={{color:n.lines[chosen.currentLineId].color}}>▣</span><strong>{chosen.number}</strong><small>{chosen.id}</small></div><span className={`badge ${chosen.movement==='BLOCKED'?'warning':'ok'}`}>{movement[chosen.movement]}</span><h3>{n.lines[chosen.currentLineId].name}</h3><p className="train-location">{location(n,chosen)}</p><dl><dt>Linha designada</dt><dd>{n.lines[chosen.assignedLineId].name}</dd><dt>Modelo</dt><dd>{chosen.model}</dd><dt>Perfil</dt><dd>{n.profiles[chosen.profileId].name}</dd><dt>Velocidade</dt><dd>{Math.round(chosen.speedKmh)} km/h</dd><dt>Espera acumulada</dt><dd>{Math.round(chosen.delaySeconds)} s</dd><dt>Composição</dt><dd>{chosen.carriages} carros · {chosen.capacity} pessoas</dd><dt>Transferência</dt><dd>{chosen.transfer==='IN_PROGRESS'?`Em curso → ${n.lines[chosen.targetLineId!]?.name}`:chosen.transfer==='COMPLETED'?'Concluída':chosen.transfer==='CANCELLED'?'Cancelada':'Nenhuma'}</dd></dl>{chosen.reason&&<div className="train-reason">{chosen.reason}</div>}{operate&&<div className="train-actions"><button className="primary" disabled={busy||!chosen.nodeId||!chosen.active} onClick={()=>void transfer(chosen)}>⇄ Planejar transferência</button>{chosen.transfer==='IN_PROGRESS'&&<button disabled={busy||!chosen.nodeId} onClick={()=>void action(`/trains/${encodeURIComponent(chosen.id)}/transfer`,undefined,'DELETE')}>Cancelar transferência</button>}<button disabled={busy||!chosen.nodeId} onClick={()=>void action(`/trains/${encodeURIComponent(chosen.id)}/active`,{active:!chosen.active},'PATCH')}>{chosen.active?'Retirar de circulação':'Colocar em circulação'}</button><button onClick={()=>setDialog({kind:'incident',target:{type:'TRAIN',id:chosen.id}})}>Registrar ocorrência</button>{!chosen.active&&<><button onClick={()=>setDialog({kind:'train',train:chosen})}>Editar composição</button><button onClick={()=>setDialog({kind:'delete',train:chosen})}>Excluir composição</button></>}{!chosen.nodeId&&<small className="muted">Aguarde a plataforma para transferir ou retirar de circulação.</small>}</div>}</>:<div className="empty-selection"><div>⌖</div><h3>Cada trem, em detalhe</h3><p>Selecione uma composição no mapa ou na frota para acompanhar sua posição e controlar a operação.</p><span className="badge">IDENTIFICAÇÃO EM TEMPO REAL</span></div>}<div className="detail-footnote">Geometria esquemática. A movimentação segue o relógio da simulação.</div></aside>
    </div>}
    {tab==='incidents'&&<section className="content-panel"><div className="section-heading"><div><span className="eyebrow">RESPOSTA OPERACIONAL</span><h2>Ocorrências e impactos</h2><p className="muted">Rótulos, causa e caminho de propagação permanecem visíveis até a resolução.</p></div><label className="check"><input type="checkbox" checked={showResolved} onChange={e=>setShowResolved(e.target.checked)}/>Mostrar resolvidas</label></div><div className="incident-list">{incidents.map(i=>{const impacts=snap.impacts.filter(v=>v.incidentId===i.id);return <article key={i.id} className={`incident-card ${i.status==='RESOLVED'?'resolved':''}`}><div className="incident-top"><span className={`severity severity-${i.severity}`}>{severity[i.severity]}</span><span className="badge">{effect[i.effect]}</span><span className="muted">{i.status==='RESOLVED'?'Resolvida':i.status==='ACKNOWLEDGED'?'Reconhecida':'Aberta'}</span><time>{new Date(i.createdAt).toLocaleString('pt-BR')}</time></div><h3>{i.label}</h3><p>{i.description}</p><div className="incident-meta">{i.category} · {i.targetId} · Por {i.createdBy}{i.acknowledgedBy?` · Atendimento: ${i.acknowledgedBy}`:''}</div><div className="impact-badges">{impacts.map(v=><span key={v.lineId} className={`badge ${v.level==='POTENTIAL'?'risk':'warning'}`} title={`${level[v.level]}: ${v.path.join(' → ')}. ${v.reason}`}>{n.lines[v.lineId].name} · {v.level==='POTENTIAL'?'risco':v.level==='DIRECT'?'direto':'operacional'}</span>)}</div><details><summary>Identificação e propagação</summary><code>{i.id}</code><ul>{impacts.map(v=><li key={v.lineId}>{level[v.level]} · {v.path.join(' → ')} · {v.reason}</li>)}</ul>{i.resolvedAt&&<p>Resolvida em {new Date(i.resolvedAt).toLocaleString('pt-BR')}</p>}</details>{operate&&i.status!=='RESOLVED'&&<div className="incident-actions">{i.status==='OPEN'&&<button disabled={busy} onClick={()=>void action(`/incidents/${i.id}/ack`,{})}>Reconhecer alerta</button>}<button disabled={busy} className="primary" onClick={()=>void action(`/incidents/${i.id}/resolve`,{})}>Marcar como resolvida</button></div>}</article>;})}{!incidents.length&&<div className="empty"><span className="empty-icon">✓</span><h3>Nenhuma ocorrência neste filtro</h3><p>Novos alertas aparecerão aqui com sua origem e as linhas afetadas.</p></div>}</div></section>}
    {tab==='infrastructure'&&admin&&<Infrastructure n={n} action={action} busy={busy}/>}
    {tab==='history'&&<section className="content-panel"><div className="section-heading"><div><span className="eyebrow">RASTREABILIDADE</span><h2>Histórico de operação</h2><p className="muted">Últimos 200 comandos persistidos. Avanços automáticos atualizam o estado sem gerar uma entrada por segundo.</p></div><span className="badge">AUDITORIA DE COMANDOS</span></div><div className="table-scroll"><table><thead><tr><th>Data e hora</th><th>Operador</th><th>Ação</th><th>Detalhe</th><th>Versão</th></tr></thead><tbody>{history.map(v=><tr key={v.id}><td>{new Date(v.at).toLocaleString('pt-BR')}</td><td>{v.actor}</td><td><code>{v.action}</code></td><td>{v.detail}</td><td>#{v.version}</td></tr>)}</tbody></table>{!history.length&&<div className="empty">Nenhum comando registrado.</div>}</div><div className="statistics"><span>Espera média: <b>{m.meanDelay.toFixed(1)} s</b></span><span>Mediana: <b>{m.medianDelay.toFixed(1)} s</b></span><span>Moda: <b>{m.modeDelay.length?m.modeDelay.map(v=>`${v.toFixed(1)} s`).join(', '):'Sem repetição'}</b></span><small>Composições ativas · espera acumulada por via ou bloqueio</small></div></section>}
    <footer className="app-footer"><span>FERROVIA <i/> Supervisão e simulação</span><span>Rede de referência: {n.referenceDate} · Dados persistidos · v1.0</span></footer>
    {error&&<div className="toast error-toast" role="alert"><strong>Operação não concluída</strong><p>{error}</p><button aria-label="Fechar mensagem" onClick={()=>setError('')}>×</button></div>}{notice&&!error&&<div className="toast notice-toast" role="status"><strong>Alerta recebido</strong><p>{notice}</p><button aria-label="Fechar alerta" onClick={()=>setNotice('')}>×</button></div>}
    {dialog?.kind==='train'&&<TrainDialog n={n} train={dialog.train} action={action} close={()=>setDialog(null)} busy={busy}/>}
    {dialog?.kind==='transfer'&&<TransferDialog n={n} train={dialog.train} action={action} close={()=>setDialog(null)} busy={busy}/>}
    {dialog?.kind==='incident'&&<IncidentDialog n={n} target={dialog.target} action={action} close={()=>setDialog(null)} busy={busy}/>}
    {dialog?.kind==='about'&&<Modal title="Referência e limites do cenário" close={()=>setDialog(null)}><p>{n.notes}</p><p>Perfis técnicos conservadores impedem rotas incompatíveis. A evidência de circulação do Serviço 710 permite demonstrar uma transferência da Linha 7 para a Linha 10. Outras integrações não possuem ligação física habilitada neste cadastro.</p><p>O menor custo considera tempo de viagem, paradas e penalidade estimada de ocupação. Os tempos não representam um horário real.</p><div className="source-links">{n.sources.map((source,i)=><a key={source} href={source} target="_blank" rel="noreferrer">{i===0?'Mapa oficial de referência':'CPTM · Serviço 710'} ↗</a>)}</div><div className="dialog-actions"><button className="primary" onClick={()=>setDialog(null)}>Entendido</button></div></Modal>}
    {dialog?.kind==='station'&&n.stations[dialog.id]&&<Modal title={n.stations[dialog.id].name} close={()=>setDialog(null)}><span className={`badge ${n.stations[dialog.id].enabled?'ok':'warning'}`}>{n.stations[dialog.id].enabled?'Estação habilitada':'Estação desativada'}</span><h3>Plataformas e linhas</h3><ul className="station-platforms">{Object.values(n.nodes).filter(v=>v.stationId===dialog.id).map(v=><li key={v.id}><span className="line-pill" style={{borderColor:n.lines[v.lineId].color}}>{n.lines[v.lineId].name} · sentido {v.direction}</span><small>{Object.values(n.trains).filter(t=>t.active&&(t.nodeId===v.id||(t.edgeId&&n.edges[t.edgeId].to===v.id))).map(t=>t.number).join(', ')||'Livre'}</small></li>)}</ul><div className="dialog-actions">{admin&&<button disabled={busy||n.running} onClick={async()=>{const s=n.stations[dialog.id];if(await action(`/infrastructure/stations/${s.id}`,{...s,enabled:!s.enabled},'PUT'))setDialog(null);}}>{n.stations[dialog.id].enabled?'Desativar estação':'Habilitar estação'}</button>}{operate&&<button className="danger" onClick={()=>setDialog({kind:'incident',target:{type:'STATION',id:dialog.id}})}>Registrar ocorrência</button>}</div>{admin&&n.running&&<small className="muted">Pause a simulação para alterar o cadastro da estação.</small>}</Modal>}
    {dialog?.kind==='delete'&&<Modal title="Excluir composição" close={()=>setDialog(null)}><p>Excluir a composição <strong>{dialog.train.number}</strong>? O sistema preserva trens associados ao histórico de ocorrências.</p><div className="dialog-actions"><button onClick={()=>setDialog(null)}>Cancelar</button><button className="danger" disabled={busy} onClick={async()=>{if(await action(`/trains/${encodeURIComponent(dialog.train.id)}`,undefined,'DELETE')){setDialog(null);setSelected('');}}}>Excluir composição</button></div></Modal>}
  </div></OperationError.Provider>;
}

