import {useState} from 'react';
import type {FormEvent} from 'react';
import type {Action,Network} from './types';
import {Modal} from './Dialogs';

type Kind='profiles'|'lines'|'stations'|'nodes'|'edges'|'dependencies';
const names:Record<Kind,string>={profiles:'Perfis técnicos',lines:'Linhas',stations:'Estações',nodes:'Plataformas',edges:'Vias e conexões',dependencies:'Dependências de alertas'};
const defaults:Record<Kind,Record<string,string|number|boolean>>={profiles:{id:'',name:'',gaugeMm:1600,power:'',signalling:'',technology:''},lines:{id:'',name:'',color:'#4ce3b5',operator:'',profileId:'',enabled:true},stations:{id:'',name:'',x:900,y:600,enabled:true},nodes:{id:'',stationId:'',lineId:'',direction:'A',enabled:true},edges:{id:'',from:'',to:'',resourceId:'',lengthMeters:1000,maxSpeedKmh:60,connection:false,verified:false,enabled:false,source:''},dependencies:{id:'',fromLine:'',toLine:'',reason:'',operational:false}};
const labels:Record<string,string>={id:'Identificador',name:'Nome',gaugeMm:'Bitola (mm; 0 para monotrilho)',power:'Sistema de alimentação',signalling:'Sistema de sinalização',technology:'Tecnologia',color:'Cor',operator:'Operador',profileId:'Perfil técnico',enabled:'Habilitado',x:'Coordenada X do mapa',y:'Coordenada Y do mapa',stationId:'Estação',lineId:'Linha',direction:'Sentido',from:'Plataforma de origem',to:'Plataforma de destino',resourceId:'Recurso físico compartilhado',lengthMeters:'Extensão (m)',maxSpeedKmh:'Velocidade máxima (km/h)',connection:'Ligação operacional entre linhas',verified:'Ligação verificada',source:'Fonte ou evidência da verificação',fromLine:'Linha de origem',toLine:'Linha dependente',reason:'Motivo da dependência',operational:'Propagar bloqueio e redução de velocidade'};
export default function Infrastructure({n,action,busy}:{n:Network;action:Action;busy:boolean}){
  const [kind,setKind]=useState<Kind>('lines'),[query,setQuery]=useState(''),[edit,setEdit]=useState<{value:Record<string,string|number|boolean>;create:boolean}|null>(null),[remove,setRemove]=useState(''),[confirmReset,setConfirmReset]=useState(false),[error,setError]=useState('');
  const rows=Object.values(n[kind]).filter(v=>JSON.stringify(v).toLocaleLowerCase().includes(query.toLocaleLowerCase()));
  function options(field:string):[string,string][]|null{
    if(['lineId','fromLine','toLine'].includes(field))return Object.values(n.lines).map(v=>[v.id,v.name]);
    if(field==='profileId')return Object.values(n.profiles).map(v=>[v.id,v.name]);
    if(field==='stationId')return Object.values(n.stations).map(v=>[v.id,v.name]);
    if(['from','to'].includes(field))return Object.values(n.nodes).map(v=>[v.id,`${n.lines[v.lineId].name} · ${n.stations[v.stationId].name} · ${v.direction}`]);
    if(field==='direction')return [['A','A · Ida'],['B','B · Volta']];return null;
  }
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!edit)return;const form=new FormData(e.currentTarget),body:Record<string,string|number|boolean>={};for(const [key,value]of Object.entries(edit.value)){body[key]=typeof value==='boolean'?form.has(key):typeof value==='number'?Number(form.get(key)):String(form.get(key)??'');}if(await action(`/infrastructure/${kind}/${encodeURIComponent(String(body.id))}`,body,edit.create?'POST':'PUT'))setEdit(null);}
  async function importFile(file:File|undefined){if(!file)return;setError('');if(file.size>5*1024*1024){setError('O arquivo excede 5 MB.');return;}try{const data=JSON.parse(await file.text());if(window.confirm('Substituir toda a rede pelo arquivo selecionado? Exporte o cenário atual antes de continuar.'))await action('/import',data);}catch{setError('Arquivo JSON inválido.');}}
  return <section className="content-panel"><div className="section-heading"><div><span className="eyebrow">CADASTRO TÉCNICO</span><h2>Infraestrutura da rede</h2><p className="muted">Pause a simulação para editar. Referências em uso e ocupações são verificadas em cada alteração.</p></div><button className="primary" disabled={n.running||busy} onClick={()=>setEdit({value:{...defaults[kind]},create:true})}>+ Novo cadastro</button></div>
    <div className="toolbar"><select aria-label="Tipo de infraestrutura" value={kind} onChange={e=>{setKind(e.target.value as Kind);setQuery('');}}>{Object.entries(names).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><input placeholder="Buscar no cadastro…" aria-label="Buscar no cadastro" value={query} onChange={e=>setQuery(e.target.value)}/><span className="muted">{rows.length} registros</span></div>
    <div className="table-scroll"><table><thead><tr><th>Identificador</th><th>Descrição / ligação</th><th>Situação</th><th>Ações</th></tr></thead><tbody>{rows.map(row=>{const v=row as unknown as Record<string,string|boolean|number>;return <tr key={String(v.id)}><td><code>{v.id}</code></td><td>{v.name||v.reason||`${v.from||v.stationId} → ${v.to||v.lineId}`}</td><td>{'enabled'in v?<span className={`badge ${v.enabled?'ok':'warning'}`}>{v.enabled?'Habilitado':'Desativado'}</span>:kind==='dependencies'?v.operational?'Operacional':'Integração de passageiros':'Perfil'}</td><td className="row-actions"><button disabled={n.running||busy} onClick={()=>setEdit({value:{...v},create:false})}>Editar</button><button disabled={n.running||busy} onClick={()=>setRemove(String(v.id))}>Excluir</button></td></tr>;})}</tbody></table>{rows.length===0&&<div className="empty">Nenhum cadastro encontrado.</div>}</div>
    <div className="backup-bar"><div><strong>Cenário e recuperação</strong><p className="muted">Importações são validadas e iniciam pausadas. O histórico de comandos é preservado.</p></div><a className="button" href="/api/v1/export" download="ferrovia-cenario.json">Exportar JSON</a><label className="button upload">Importar JSON<input type="file" accept="application/json,.json" disabled={busy} onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/></label><button onClick={()=>setConfirmReset(true)} disabled={busy}>Restaurar referência</button></div>{error&&<p className="error-box" role="alert">{error}</p>}
    {edit&&<Modal title={`${edit.create?'Novo cadastro':'Editar cadastro'} · ${names[kind]}`} close={()=>setEdit(null)}><form onSubmit={save} className="form-grid">{Object.entries(edit.value).map(([key,value])=>{const choices=options(key);return <label key={key} className={typeof value==='boolean'?'check':key==='source'||key==='reason'?'span-2':''}>{typeof value==='boolean'?<><input type="checkbox" name={key} defaultChecked={value}/>{labels[key]}</>:<>{labels[key]}{choices?<select name={key} defaultValue={String(value)} required><option value="" disabled>Selecione…</option>{choices.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>:<input name={key} type={typeof value==='number'?'number':key==='color'?'color':'text'} step={typeof value==='number'?'any':undefined} defaultValue={String(value)} readOnly={key==='id'&&!edit.create} required={key!=='source'} maxLength={key==='source'?1000:300}/>}</>}</label>;})}<div className="dialog-actions span-2"><button type="button" onClick={()=>setEdit(null)}>Cancelar</button><button className="primary" disabled={busy}>Salvar cadastro</button></div></form></Modal>}
    {remove&&<Modal title="Excluir cadastro" close={()=>setRemove('')}><p>Excluir <strong>{remove}</strong>? Cadastros referenciados por trens, vias ou ocorrências não podem ser excluídos.</p><div className="dialog-actions"><button onClick={()=>setRemove('')}>Cancelar</button><button className="danger" disabled={busy} onClick={async()=>{if(await action(`/infrastructure/${kind}/${encodeURIComponent(remove)}`,undefined,'DELETE'))setRemove('');}}>Excluir cadastro</button></div></Modal>}
    {confirmReset&&<Modal title="Restaurar cenário de referência" close={()=>setConfirmReset(false)}><p>A rede, a frota e as ocorrências atuais serão substituídas pelo cenário histórico de 2024. Exporte os dados antes de continuar.</p><div className="dialog-actions"><button onClick={()=>setConfirmReset(false)}>Cancelar</button><button className="danger" disabled={busy} onClick={async()=>{if(await action('/reset',{}))setConfirmReset(false);}}>Restaurar cenário</button></div></Modal>}
  </section>;
}
